/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.knightstour.ui;

import br.beholder.knightstour.control.NormalPathController;
import br.beholder.knightstour.ui.swing.webLaf.PSOutTabbedPaneUI;
import br.beholder.knightstour.ui.swing.webLaf.WeblafUtils;
import br.beholder.knightstour.ui.utils.ColorController;
import com.alee.laf.combobox.WebComboBox;
import java.awt.Point;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author lite
 */
public class MainPanel extends javax.swing.JPanel {
    
    int pX, pY;
    NormalPathController controller;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        setIcon();
        configureTheme();
        controller = new NormalPathController(this);
    }
    private void setIcon(){
        
    }
    
    private void configureTheme(){
        WeblafUtils.instalaWeblaf();
        WeblafUtils.configuraWebLaf(comboBoxAlgoritmo);
        WeblafUtils.configuraWeblaf(jPanel2);
        WeblafUtils.configuraWebLaf(jTextField1);
        WeblafUtils.configuraWebLaf(jTextField4);
        WeblafUtils.configuraWebLaf(jTextField3);
        WeblafUtils.configuraWebLaf(jTextField5);
        WeblafUtils.configuraWebLaf(jTextArea1);
        WeblafUtils.configuraWeblaf(timePanel, ColorController.COR_PRINCIPAL, false, false, false, false);
        WeblafUtils.configuraWeblaf(sizePanel, ColorController.COR_PRINCIPAL, false, false, false, false);
        WeblafUtils.configuraWeblaf(positionPanel, ColorController.COR_PRINCIPAL, false, false, false, false);
        
        WeblafUtils.configuraWebLaf(jScrollPane1);
        
        jTabbedPane1.setUI(new PSOutTabbedPaneUI());
        
        WeblafUtils.configurarBotao(webButton5, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(webButton2, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        WeblafUtils.configurarBotao(webButton3, ColorController.COR_DESTAQUE, ColorController.COR_LETRA);
        
//        WeblafUtils.configurarBotao(webButton3, ColorController.COR_PRINCIPAL, ColorController.COR_LETRA,ColorController.FUNDO_CLARO, Color.orange, 5);
        
        jLabel1.setForeground(ColorController.COR_LETRA);
        jLabel2.setForeground(ColorController.COR_LETRA);
        jLabel3.setForeground(ColorController.COR_LETRA);
        jLabel4.setForeground(ColorController.COR_LETRA);
        jPanel2.setBackground(ColorController.COR_PRINCIPAL);
        jPanel7.setBackground(ColorController.COR_PRINCIPAL);
        jTextArea1.setBackground(ColorController.COR_PRINCIPAL);
        setBackground(ColorController.COR_PRINCIPAL);
        jTextArea1.setForeground(ColorController.COR_LETRA);
//        jPanel3.setBackground(ColorController.COR_PRINCIPAL); 
        jTabbedPane1.setForeground(ColorController.COR_LETRA);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        positionPanel = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sizePanel = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboBoxAlgoritmo = new com.alee.laf.combobox.WebComboBox();
        webButton2 = new com.alee.laf.button.WebButton();
        webButton3 = new com.alee.laf.button.WebButton();
        webButton5 = new com.alee.laf.button.WebButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(1024, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel2.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jTextField4.setText("7");
        jTextField4.setMinimumSize(new java.awt.Dimension(6, 10));
        jTextField4.setPreferredSize(new java.awt.Dimension(25, 35));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        positionPanel.add(jTextField4);

        jLabel3.setText("x");
        positionPanel.add(jLabel3);

        jTextField3.setText("7");
        jTextField3.setMinimumSize(new java.awt.Dimension(6, 10));
        jTextField3.setPreferredSize(new java.awt.Dimension(25, 35));
        positionPanel.add(jTextField3);

        jLabel2.setText("Posicao Inicial");
        positionPanel.add(jLabel2);

        jPanel5.add(positionPanel);

        jTextField5.setText("8");
        jTextField5.setMinimumSize(new java.awt.Dimension(6, 10));
        jTextField5.setPreferredSize(new java.awt.Dimension(25, 35));
        sizePanel.add(jTextField5);

        jLabel1.setText("Tamanho do tabuleiro");
        sizePanel.add(jLabel1);

        jPanel5.add(sizePanel);

        jTextField1.setText("100");
        jTextField1.setPreferredSize(new java.awt.Dimension(30, 35));
        timePanel.add(jTextField1);

        jLabel4.setText("Tempo entre interações");
        timePanel.add(jLabel4);

        jPanel5.add(timePanel);

        comboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BackTracking1", "BackTracking2", "Warnsdorf" }));
        comboBoxAlgoritmo.setMinimumSize(new java.awt.Dimension(56, 30));
        jPanel5.add(comboBoxAlgoritmo);

        webButton2.setText("Criar Mapa");
        webButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton2);

        webButton3.setText("Mapa Random");
        webButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton3);

        webButton5.setText("Calcular");
        webButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(webButton5);

        jPanel2.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTabbedPane1.addTab("Console", jScrollPane1);

        jSplitPane1.setBottomComponent(jTabbedPane1);

        jPanel7.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setTopComponent(jPanel7);

        jPanel2.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    public JPanel getImagePane(){
        return jPanel7;
    }

    public WebComboBox getComboBoxAlgoritmo() {
        return comboBoxAlgoritmo;
    }
    
    
    public JTextArea getConsoleArea(){
        return jTextArea1;
    }
    
    public Integer getTime(){
        return Integer.parseInt(jTextField1.getText());
    }
    
    public void setBoardSize(int size){
        jTextField5.setText(size+"");
    }
    
    public String getCalcType(){
        return comboBoxAlgoritmo.getSelectedItem().toString();
    }
    
    public Integer getBoardSize(){
        return Integer.parseInt(jTextField5.getText());
    }
    
    public Point getInicialPosition(){
        return new Point(Integer.parseInt(jTextField4.getText()), Integer.parseInt(jTextField3.getText()));
    }
    
    private void webButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton5ActionPerformed
        controller.calculate();
    }//GEN-LAST:event_webButton5ActionPerformed

    private void webButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton2ActionPerformed
        controller.createMap(getBoardSize(), getInicialPosition());
    }//GEN-LAST:event_webButton2ActionPerformed

    private void webButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton3ActionPerformed
        controller.randomMap();
    }//GEN-LAST:event_webButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.combobox.WebComboBox comboBoxAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JPanel sizePanel;
    private javax.swing.JPanel timePanel;
    private com.alee.laf.button.WebButton webButton2;
    private com.alee.laf.button.WebButton webButton3;
    private com.alee.laf.button.WebButton webButton5;
    // End of variables declaration//GEN-END:variables
}
